version: "3.8"
services:
  db:
      image: postgres
      restart: always
      env_file: 
        - ./envs/.env
      volumes:
        - ./data:/var/lib/postgresql/data
      ports:
        - 5432:5432

  rabbitmq:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    command: celery -A main worker --loglevel=info
    depends_on:
      - rabbitmq
      - redis
      - db
    volumes:
      - .:/app/
    working_dir: /app/src

  fastapi_app:
    build: .
    command: python3 main.py
    depends_on:
      - rabbitmq
      - redis
      - db
    volumes:
      - .:/app/
    working_dir: /app/src
    ports:
      - "8000:8000"
