version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    command: celery -A main worker --loglevel=info
    depends_on:
      - rabbitmq
      - redis
    volumes:
      - .:/app/
    working_dir: /app/src
